In [3]:
import numpy as np
import pandas as pd
import scipy.stats as st
import matplotlib.pyplot as plt
import PMTPosition as PMT

In [4]:
GEM_width,  GEM_height = PMT.GetGEMsDim()
GEM_z_dist = PMT.GetGEMsZ()
print(GEM_width,  GEM_height, GEM_z_dist)


50.0 80.0 59.0


In [4]:
pos = PMT.GenEventPosition(x_offset = 0.0, y_offset = 0.0, size = 10, distribution = 'uniform')

In [5]:
pos

array([[ 7.09259555,  5.12417455],
       [42.85624014, 33.35098976],
       [37.31427914, 39.69600984],
       [35.79526661, 29.76109994],
       [47.85655936, 64.51972875],
       [48.15586501, 17.31932856],
       [30.32561726,  6.63237398],
       [ 6.55510875,  7.48612347],
       [29.93467797, 39.72831071],
       [12.68127593, 57.22374614]])

In [6]:
R = PMT.GetR(PMT_pos = np.array([25.0, 40.0]), Event_pos = pos)

In [7]:
R

array([70.83783124, 62.00044072, 60.27216506, 60.84712693, 67.85749335,
       67.31721133, 67.99088663, 69.84530178, 59.20662853, 62.68499337])

In [8]:
PMT_pos = np.array([[25.0, 20.0], [25.0, 60.0]])
R_all   = PMT.GetR_All(PMT_pos = PMT_pos, Event_pos = pos)

In [9]:
R_all.shape

(10, 2)

In [10]:
R_all

array([[63.42685013, 82.54108888],
       [63.0721352 , 67.15664568],
       [63.4079985 , 63.5994771 ],
       [60.76855152, 67.17089294],
       [77.36555147, 63.43382578],
       [63.43800189, 76.4122621 ],
       [60.72936377, 79.7337175 ],
       [63.06989075, 81.11054951],
       [62.40638822, 62.5802879 ],
       [70.84037154, 60.33621258]])

In [11]:
ints = PMT.GetIntegrals(R_all, energy = 5.9, LY = 8500.0)

In [12]:
ints

array([[1.58652138e-04, 5.53168867e-05],
       [1.62251369e-04, 1.26235795e-04],
       [1.58840895e-04, 1.56936631e-04],
       [1.88288140e-04, 1.26128729e-04],
       [7.16717490e-05, 1.58582363e-04],
       [1.58540609e-04, 7.53158320e-05],
       [1.88774609e-04, 6.35287708e-05],
       [1.62274466e-04, 5.93238230e-05],
       [1.69286494e-04, 1.67412653e-04],
       [1.01956562e-04, 1.93743136e-04]])

In [2]:
print('python sucks')

python sucks
