In [1]:
import numpy as np
import pandas as pd
import scipy.stats as st
import matplotlib.pyplot as plt

In [2]:
import PMTPosition as PMT

In [3]:
GEM_width,  GEM_height = PMT.GetGEMsDim()
print(GEM_width,  GEM_height)

50.0 80.0


In [4]:
pos = PMT.GenEventPosition(x_offset = 0.0, y_offset = 0.0, size = 10, distribution = 'uniform')

In [5]:
pos

array([[37.87249855, 59.42557809],
       [36.52893139, 67.60211157],
       [45.11249937, 36.28338729],
       [ 7.57192211, 17.23345521],
       [46.14063884, 37.73606315],
       [16.39629334,  5.09808321],
       [30.28392402, 15.94642315],
       [37.70089923, 52.47369387],
       [40.24859787, 15.64708345],
       [12.61094343, 10.02633452]])

In [6]:
R = PMT.GetR(PMT_pos = np.array([25.0, 40.0]), Event_pos = pos)

In [7]:
R

array([64.366562  , 67.04321608, 63.39026614, 66.49852224, 63.65573046,
       69.94403165, 64.85749311, 62.58518898, 66.52506506, 68.20490705])

In [8]:
PMT_pos = np.array([[25.0, 20.0], [25.0, 60.0]])
R_all   = PMT.GetR_All(PMT_pos = PMT_pos, Event_pos = pos)

In [9]:
R_all.shape

(10, 2)

In [10]:
R_all

array([[72.93886088, 61.36799801],
       [77.45241949, 61.56872875],
       [65.34264559, 67.57951131],
       [62.54111983, 75.71469641],
       [66.04161223, 67.39888348],
       [62.41867423, 81.78168643],
       [60.36846311, 74.62330391],
       [69.39635174, 61.78962797],
       [62.06019352, 76.15576763],
       [62.07223796, 79.06235491]])

In [11]:
ints = PMT.GetIntegrals(R_all, energy = 5.9, LY = 8500.0)

In [12]:
ints

array([[9.40818346e-06, 1.87747369e-05],
       [7.39948898e-06, 1.85310888e-05],
       [1.46067914e-05, 1.27667836e-05],
       [1.74052021e-05, 8.10253549e-06],
       [1.39981620e-05, 1.29041937e-05],
       [1.75421784e-05, 5.95274715e-06],
       [2.00493919e-05, 8.58704602e-06],
       [1.14814073e-05, 1.82675103e-05],
       [1.79510221e-05, 7.91645018e-06],
       [1.79370933e-05, 6.81495041e-06]])