In [1]:
import numpy as np
import pandas as pd
import scipy.stats as st
import matplotlib.pyplot as plt

In [2]:
import PMTPosition as PMT

In [3]:
GEM_width,  GEM_height = PMT.GetGEMsDim()
print(GEM_width,  GEM_height)

50.0 80.0


In [4]:
pos = PMT.GenEventPosition(x_offset = 0.0, y_offset = 0.0, size = 10, distribution = 'uniform')

In [5]:
pos

array([[12.05556541, 12.20397334],
       [18.12305566, 56.05909648],
       [ 8.38344564, 66.93955785],
       [16.72144463, 67.0442327 ],
       [24.50103197, 67.54255927],
       [34.58446555, 46.05637893],
       [ 3.74471026, 53.14113533],
       [38.36815463, 42.11709012],
       [ 3.46038241,  2.30309987],
       [32.19076199, 46.21973179]])

In [6]:
R = PMT.GetR(PMT_pos = np.array([25.0, 40.0]), Event_pos = pos)

In [7]:
R

array([67.38083915, 62.49149497, 67.83693431, 66.33193048, 66.02152331,
       61.06178597, 64.9959751 , 61.50763878, 74.06086285, 60.74859769])

In [8]:
PMT_pos = np.array([[25.0, 20.0], [25.0, 60.0]])
R_all   = PMT.GetR_All(PMT_pos = PMT_pos, Event_pos = pos)

In [9]:
R_all.shape

(10, 2)

In [10]:
R_all

array([[61.87355185, 77.79472059],
       [70.33882856, 60.52126142],
       [77.97071226, 62.64397291],
       [76.69220501, 60.97668155],
       [76.55418937, 60.47428519],
       [66.11200241, 62.34008781],
       [71.76435183, 64.02211623],
       [65.32896167, 64.01957532],
       [66.15992292, 85.98190165],
       [65.87246309, 61.98066513]])